version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: #{DB_USERNAME}
      POSTGRES_PASSWORD: #{DB_PASSWORD}
      POSTGRES_DB: pipeline_learning_development

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
