default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: <%= ENV.fetch('DB_USERNAME') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pipeline_learning_development
  username: <%= ENV.fetch('DB_USERNAME') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>
test:
  <<: *default
  database: pipeline_learning_test
  username: <%= ENV.fetch('TEST_DB_USERNAME') %>
  password: <%= ENV.fetch('TEST_DB_PASSWORD') %>

production:
  <<: *default
  database: pipeline_learning_production
  username: <%= ENV.fetch('PRODUCTION_DB_USERNAME') %>
  password: <%= ENV.fetch('PRODUCTION_DB_PASSWORD') %>
  host: <%= ENV.fetch('PRODUCTION_DB_HOST') %>
