name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: db
          TEST_DB_USERNAME: postgres
          TEST_DB_PASSWORD: postgres
        ports:
          - 5432:5432
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgresql://postgres@localhost/pipeline_learning_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: Wait for PostgreSQL to be ready
        run: docker-compose build
      - name: Run docker compose
        run: docker-compose up
      - name: Create PostgreSQL database
        run: docker-compose run web rails db:create
